tasks:
  - name: setup
    before: |
      echo "Setting up, please wait!"
      cd /workspace/quarkus-astra-intro-demo 
      sed -i '1,$s/sdkman_auto_answer=false/sdkman_auto_answer=true/' /home/gitpod/.sdkman/etc/config 
      sed -i '1,$s/sdkman_selfupdate_enable=true/sdkman_selfupdate_enable=false/' /home/gitpod/.sdkman/etc/config 
      sdk install java 22.0.0.2.r11-grl -y
      export GRAALVM_HOME=$JAVA_HOME
      "$GRAALVM_HOME"/bin/gu install native-image
      sudo apt-get install --reinstall xdg-utils --fix-missing -y
      sudo apt-get update
      sudo apt-get install -y apt-transport-https ca-certificates curl
      sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg      
      echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
      sudo apt-get update
      sudo apt-get install -y kubectl
      wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.8.0.63668.zip
      unzip sonarqube-9.8.0.63668.zip
      PATH=/workspace/quarkus-astra-intro-demo/sonarqube-9.8.0.63668/bin/linux-x86-64/:$PATH
      sonar.sh start
ports:
  - port: 5005
  - port: 8080
  - port: 8081
  - port: 9000
  - port: 9001
  - port: 9002
  - port: 9092
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - redhat.java
    - github.vscode-pull-request-github
    - gabrielbb.vscode-lombok
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - SonarSource.sonarlint-vscode
